(define (fib n)
  (define (fof n a b)
    (cond ((= n 0) a)
	  ((= n 1) b)
	  (#t (fof (- n 1) b (+ a b)))))
  (fof n 0 1))
(define num (string->number (if (eof-object? in) (error "Requires input") in)))
(if (number? num) (displayln (fib num)) (error "Input not a number")))
