(define (addition x y)
  (define sum (+ x y))
  (displayln sum))
(define inX (read-line))
(define inY (read-line))
(define x (string->number (if (eof-object? inX) (error "Requires input") inX)))
(define y (string->number (if (eof-object? inY) (error "Requires input") inY)))
(if (and (number? x) (number? y)) (addition x y) (error "Input not a number"))
